In [12]:
import pandas as pd
import re

In [7]:
data1 = pd.read_csv(r"C:\\Personal-space\\projects\\source1_naukri_applicants.csv")
data1.sample(5)

,Full Name,Email,Phone,City,Experience (Years),Current CTC,Applied Date,Skills
24,Sneha Mishra,sneha.mishra14@mailtest.example.org,9000000229,pune,1.4,410629.0,15-06-2026,"MySQL, Docker, Selenium, Pandas"
26,Priya Saxena,priya.saxena61@example.com,919000000231,Delhi,5.0,6.6,08/16/2026,"Python, MySQL, Zapier, React"
5,Sahil Malhotra,sahil.malhotra1@example.in,919000000143,Noida,1.7,806661.0,07/13/2026,"FastAPI, Docker, MySQL, Zapier, Pandas, REST APIs"
25,Nikhil Chopra,alt.nikhil.chopra70@example.com,9000000103,NOIDA,0.8,7.8,07/03/2026,"Pandas, SQL, n8n"
41,Neha Bhatia,neha.bhatia60@mailtest.example.org,9000000273,Pune,4.2,694306.0,22 Jul 2026,"FastAPI, Zapier, JavaScript, Selenium"

In [9]:
data2 = pd.read_csv(r"C:\\Personal-space\\projects\\source2_gig_workers.csv")
data2.sample(5)

,email_id,worker_name,rate,location,status,skill_tags
21,vikram.mehta6@example.com,Vikram Mehta,22k/month,pune,ACTIVE,"rest apis, python, langchain"
17,manish.bhatia3@example.com,Manish Bhatia,73k/month,Noida,ACTIVE,"pandas, docker, javascript, react, rest apis, ..."
6,meera.bhatia52@mailtest.example.org,Meera Bhatia,330/hr,New Delhi,active,"langchain, docker, mysql, python, sql, react"
11,VARUN.SAXENA21@EXAMPLE.IN,Varun Saxena,917/hr,gurugram,Inactive,"mongodb, zapier, sql, langchain, mysql, rest apis"
7,vikram.saxena60@example.com,Vikram Saxena,843/hr,Gurgaon,Active,"selenium, web scraping, react, docker, sql, fa..."

In [10]:
data3 = pd.read_csv(r"C:\\Personal-space\\projects\\source3_cbnexus_contacts.csv")
data3.sample(5)

             Name    Phone Number     City Verified Projects Completed
12   KARAN BHATIA      9000000211    NOIDA      yes                  2
18  Vikram Saxena      9000000113  Gurgaon       No                 15
21   VARUN SAXENA    919000000170  GURGAON        Y                  1
11  Tanvi Agarwal    919000000148     Pune        N                  3
8    Shreya Gupta  +91-9000000227    NOIDA      yes                 13

In [11]:
data1.info(), data2.info(), data3.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Full Name           42 non-null     str
 1   Email               42 non-null     str
 2   Phone               42 non-null     int64
 3   City                42 non-null     str
 4   Experience (Years)  42 non-null     float64
 5   Current CTC         42 non-null     float64
 6   Applied Date        42 non-null     str
 7   Skills              42 non-null     str
dtypes: float64(2), int64(1), str(5)
memory usage: 2.8 KB
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   email_id     31 non-null     str
 1   worker_name  31 non-null     str
 2   rate         31 non-null     str
 3   location     31 non-null     str
 4   status       31 non-null     str
 5   skill_tags   31 non-null     str
dtypes: str(6)
memory usage: 1.6 KB
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                31 non-null     str
 1   Phone Number        31 non-null     str
 2   City                31 non-null     str
 3   Verified            31 non-null     str
 4   Projects Completed  31 non-null     str
dtypes: str(5)
memory usage: 1.3 KB

(None, None, None)

In [21]:
data1["City"].unique(), data2["location"].unique(), data3["City"].unique()

(<StringArray>
 ['Bengaluru',   'GURGAON',      'pune',     'Noida',     'NOIDA',      'PUNE',
  'gurugram ',     'Delhi', 'new delhi',    'Noida ', 'New Delhi', 'Delhi NCR',
       'Pune', 'Bangalore',  'Gurugram', 'bangalore']
 Length: 16, dtype: str,
 <StringArray>
 [     'Pune',      'PUNE',    'Noida ',     'Delhi', 'New Delhi',   'Gurgaon',
      'Noida', 'bangalore',         nan, 'gurugram ',      'pune', 'Bengaluru',
    '1406/hr',     'NOIDA', 'new delhi']
 Length: 15, dtype: str,
 <StringArray>
 [  'Gurgaon',    'Noida ', 'New Delhi',     'Noida',      'pune', 'Delhi NCR',
      'NOIDA', 'gurugram ',      'Pune', 'new delhi',      'City',     'Delhi',
  'Bengaluru',   'GURGAON',      'PUNE']
 Length: 15, dtype: str)

In [37]:
data1["Experience (Years)"].mean(), data1["Experience (Years)"].median()

(np.float64(3.314285714285714), np.float64(3.2))

In [72]:
def extract_unique_skills(data, skill_column="Skills"):
    """
    Extract all unique skills from a DataFrame.

    - Searches the specified skills column
    - Splits comma, |, ; and / separated values
    - Converts to lowercase
    - Strips whitespace
    - Removes duplicates
    """

    unique_skills = set()

    for value in data[skill_column]:

        if pd.isna(value):
            continue

        # Convert to string
        value = str(value).strip()

        if not value:
            continue

        # Split skills using common delimiters
        skills = re.split(r"[,|;/]", value)

        for skill in skills:

            skill = skill.strip().lower()

            if skill:
                unique_skills.add(skill)

    return sorted(unique_skills)

In [76]:
skills1 = extract_unique_skills(data1, "Skills")
skills2 = extract_unique_skills(data2, "skill_tags")

all_skills = set(skills1 + skills2)
# print(skills1)
# print(skills2)
print(all_skills)

{'pandas', 'rest apis', 'mysql', 'fastapi', 'javascript', 'zapier', 'react', 'docker', 'web scraping', 'sql', 'langchain', 'python', 'mongodb', 'active', 'selenium', 'n8n'}

['docker', 'fastapi', 'javascript', 'langchain', 'mongodb', 'mysql', 'n8n', 'pandas', 'python', 'react', 'rest apis', 'selenium', 'sql', 'web scraping', 'zapier']

['active', 'docker', 'fastapi', 'javascript', 'langchain', 'mongodb', 'mysql', 'n8n', 'pandas', 'python', 'react', 'rest apis', 'selenium', 'sql', 'web scraping', 'zapier']

# Email

In [ ]:
EMAIL_PATTERN = re.compile(
    r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
)

def normalize_email(value):
    """Normalize a single email value."""
    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if not value:
        return None

    return value


def is_valid_email(value):
    """Check whether a value is a valid email."""
    if not value:
        return False

    return bool(EMAIL_PATTERN.match(value))


def find_email(row, email_column="Email", visited_columns=None):
    """
    Find and normalize an email for one row.

    1. Check the expected email column first.
    2. If invalid/missing, search other unvisited columns.
    3. Return the email and the column where it was found.
    """

    # --------------------------------
    # 1. Check expected email column
    # --------------------------------
    if (
        email_column in row.index
        and email_column not in visited_columns
    ):
        email = normalize_email(row[email_column])

        if is_valid_email(email):
            return email, email_column

    # --------------------------------
    # 2. Search other unvisited columns
    # --------------------------------
    for column in row.index:

        if column == email_column:
            continue

        if column in visited_columns:
            continue

        value = normalize_email(row[column])

        if is_valid_email(value):
            return value, column

    return None, None


# def process_emails(df, email_column="Email"):
#     """Find, normalize and validate emails for the entire DataFrame."""

#     df = df.copy()

#     df["email"] = df.apply(
#         lambda row: find_email(row, email_column),
#         axis=1
#     )

#     # df["email_valid"] = df["email"].notna()

#     return df

# Phone

In [95]:
def normalize_phone(value):
    if pd.isna(value):
        return None

    value = str(value).strip()

    # Allow only a trailing .0 caused by pandas/Excel
    if re.fullmatch(r"\d+\.0", value):
        value = value[:-2]

    # If decimal occurs anywhere else, reject it
    elif "." in value:
        return None

    # Remove non-digit characters
    digits = re.sub(r"\D", "", value)

    # Handle +91 / 91
    if digits.startswith("91") and len(digits) == 12:
        digits = digits[2:]

    # Must be exactly 10 digits
    if len(digits) != 10:
        return None

    # Indian mobile number
    if digits[0] not in "6789":
        return None

    return f"+91-{digits}"


def find_phone(row, phone_column="Phone", visited_columns=None):

    if visited_columns is None:
        visited_columns = set()

    # Check expected Phone column first
    if (
        phone_column in row.index
        and phone_column not in visited_columns
    ):

        phone = normalize_phone(row[phone_column])

        if phone is not None:
            return phone, phone_column

    # Search other columns
    for column in row.index:

        if column == phone_column:
            continue

        if column in visited_columns:
            continue

        phone = normalize_phone(row[column])

        if phone is not None:
            return phone, column

    return None, None

# City

In [97]:
CITY_MAPPING = {
    "bengaluru": "bengaluru",
    "bangalore": "bengaluru",

    "gurgaon": "gurugram",
    "gurugram": "gurugram",

    "pune": "pune",

    "noida": "noida",

    "delhi": "delhi",
    "new delhi": "delhi",
    "delhi ncr": "delhi",
}


def normalize_city(value):
    """
    Normalize a city value and map it to a canonical city.
    Returns None if the value is invalid.
    """

    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if not value:
        return None

    # Reject numeric values
    if re.search(r"\d", value):
        return None

    # Map to canonical city
    return CITY_MAPPING.get(value)


def find_city(row, city_column="City", visited_columns=None):

    if visited_columns is None:
        visited_columns = set()

    # Check expected City column
    if (
        city_column in row.index
        and city_column not in visited_columns
    ):

        city = normalize_city(row[city_column])

        if city is not None:
            return city, city_column

    # Search other columns
    for column in row.index:

        if column == city_column:
            continue

        if column in visited_columns:
            continue

        city = normalize_city(row[column])

        if city is not None:
            return city, column

    return None, None

# Experience

In [98]:
def normalize_experience(value):

    if pd.isna(value):
        return None

    # It should be a number (int or float)
    if not isinstance(value, (int, float)):
        return None

    if value < 0 or value > 6:
        return None

    return value


def find_experience(
    row,
    experience_column="Experience (Years)",
    visited_columns=None
):

    if visited_columns is None:
        visited_columns = set()

    # Expected column first
    if (
        experience_column in row.index
        and experience_column not in visited_columns
    ):

        experience = normalize_experience(
            row[experience_column]
        )

        if experience is not None:
            return experience, experience_column

    # Search other columns
    for column in row.index:

        if column == experience_column:
            continue

        if column in visited_columns:
            continue

        experience = normalize_experience(row[column])

        if experience is not None:
            return experience, column

    return None, None

# Current CTC

In [100]:
def normalize_ctc(ctc):
    if pd.isna(ctc):
        return None

    if ctc > 100:
        return int(ctc / 10000) / 10

    return ctc


def find_ctc(
    row,
    ctc_column="Current CTC",
    visited_columns=None
):

    if visited_columns is None:
        visited_columns = set()

    # Expected column first
    if (
        ctc_column in row.index
        and ctc_column not in visited_columns
    ):

        ctc = normalize_ctc(row[ctc_column])

        if ctc is not None:
            return ctc, ctc_column

    # Search other columns
    for column in row.index:

        if column == ctc_column:
            continue

        if column in visited_columns:
            continue

        ctc = normalize_ctc(row[column])

        if ctc is not None:
            return ctc, column

    return None, None

# Date

In [101]:
def normalize_date(date):
    if pd.isna(date):
        return None

    date = pd.to_datetime(
        date,
        errors="coerce",
        dayfirst=True
    )

    if pd.isna(date):
        return None

    return date.date()


def find_date(
    row,
    date_column="Applied Date",
    visited_columns=None
):

    if visited_columns is None:
        visited_columns = set()

    # Expected column first
    if (
        date_column in row.index
        and date_column not in visited_columns
    ):

        date = normalize_date(row[date_column])

        if date is not None:
            return date, date_column

    # Search other columns
    for column in row.index:

        if column == date_column:
            continue

        if column in visited_columns:
            continue

        date = normalize_date(row[column])

        if date is not None:
            return date, column

    return None, None

# Skills

In [77]:
KNOWN_SKILLS = {
    'pandas', 
    'rest apis', 
    'mysql', 
    'fastapi', 
    'javascript', 
    'zapier', 
    'react', 
    'docker', 
    'web scraping', 
    'sql', 
    'langchain', 
    'python', 
    'mongodb', 
    'selenium', 
    'n8n'
}

In [104]:
def normalize_skills(skills):
    """
    Normalize skills:
    - Convert to string/list
    - Convert to lowercase
    - Strip whitespace
    - Remove duplicates
    - Return a list of unique skills
    """

    if pd.isna(skills):
        return []

    # Handle list / array values
    if isinstance(skills, (list, tuple, set)):
        values = skills
    else:
        # Convert to string
        skills = str(skills).strip()

        if not skills:
            return []

        # Split on common delimiters
        values = re.split(r"[,|;/]", skills)

    # Normalize and remove duplicates
    unique_skills = set()

    for skill in values:

        skill = str(skill).strip().lower()

        if skill:
            unique_skills.add(skill)

    # Return sorted list for consistent output
    return sorted(unique_skills)



def find_skills(
    row,
    skill_column="Skills",
    visited_columns=None
):

    if visited_columns is None:
        visited_columns = set()

    all_skills = []
    source_columns = set()

    # ----------------------------------------
    # Check expected Skills column first
    # ----------------------------------------

    if (
        skill_column in row.index
        and skill_column not in visited_columns
    ):

        skills = normalize_skills(row[skill_column])

        valid_skills = [
            skill for skill in skills
            if skill in KNOWN_SKILLS
        ]

        if valid_skills:
            all_skills.extend(valid_skills)
            source_columns.add(skill_column)

            return all_skills, source_columns

    # ----------------------------------------
    # Search other columns
    # ----------------------------------------

    for column in row.index:

        if column == skill_column:
            continue

        if column in visited_columns:
            continue

        skills = normalize_skills(row[column])

        valid_skills = [
            skill for skill in skills
            if skill in KNOWN_SKILLS
        ]

        if valid_skills:
            all_skills.extend(valid_skills)
            source_columns.add(column)

    # Remove duplicates
    all_skills = sorted(set(all_skills))

    return all_skills, source_columns

# Name

In [105]:
def normalize_name(name):
    """
    Normalize and validate a person's name.

    Returns:
        normalized lowercase name if valid
        None if invalid
    """

    if pd.isna(name):
        return None

    # Convert to string and normalize whitespace
    name = str(name).strip().lower()
    name = re.sub(r"\s+", " ", name)

    if not name:
        return None

    # Name should not contain numbers
    if re.search(r"\d", name):
        return None

    # Name should not contain @
    if "@" in name:
        return None

    # Allow letters, spaces, apostrophes and hyphens
    if not re.fullmatch(r"[a-zA-Z]+(?:[\s'-][a-zA-Z]+)*", name):
        return None

    return name


def find_name(row, visited_columns=None, name_column="Full Name"):

    if visited_columns is None:
        visited_columns = set()

    if name_column in row.index and name_column not in visited_columns:

        name = normalize_name(row[name_column])

        if name is not None:
            return name, name_column

    # --------------------------------
    # 2. Search other unvisited columns
    # --------------------------------
    for column in row.index:

        if column == name_column:
            continue

        if column in visited_columns:
            continue

        name = normalize_name(row[column])

        if name is not None:
            return name, column

    return None, None

# Rate

In [117]:
def normalize_rate(value):
    """
    Normalize rate to INR per month and return in k/month format.

    Examples:
        440/hr       -> "91.52k/month"
        1406/hr      -> "292.45k/month"
        32k/month    -> "32k/month"
        32000/month  -> "32k/month"
    """

    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if not value:
        return None

    # Extract number + optional unit
    match = re.search(
        r"(\d+(?:\.\d+)?)\s*(k|thousand|l|lakh|lac)?",
        value
    )

    if not match:
        return None

    number = float(match.group(1))
    unit = match.group(2)

    # Convert unit to INR
    if unit in ("k", "thousand"):
        number *= 1_000

    elif unit in ("l", "lakh", "lac"):
        number *= 100_000

    # Convert to monthly rate
    if re.search(r"\b(hour|hr|hourly)\b", value):

        # 8 hours/day × 26 working days/month
        monthly_rate = number * 8 * 26

    elif re.search(r"\b(month|monthly|mo)\b", value):

        monthly_rate = number

    else:
        return None

    if monthly_rate <= 0:
        return None

    # Convert to k
    monthly_k = monthly_rate / 1000

    # Remove unnecessary decimal zeros
    return f"{monthly_k:g}k/month"


def find_rate(row, rate_column="Rate", visited_columns=None):
    """
    Find and normalize rate.

    1. Check expected Rate column first.
    2. If invalid/missing, search other unvisited columns.
    3. Return normalized rate and source column.
    """

    if visited_columns is None:
        visited_columns = set()

    # ----------------------------------------
    # 1. Check expected Rate column
    # ----------------------------------------

    if (
        rate_column in row.index
        and rate_column not in visited_columns
    ):

        rate = normalize_rate(row[rate_column])

        if rate is not None:
            return rate, rate_column

    # ----------------------------------------
    # 2. Search other columns
    # ----------------------------------------

    for column in row.index:

        if column == rate_column:
            continue

        if column in visited_columns:
            continue

        rate = normalize_rate(row[column])

        if rate is not None:
            return rate, column

    return None, None

# Status

In [118]:
VALID_STATUSES = {"active", "inactive", "paused"}

In [119]:
def normalize_status(value):
    """
    Normalize and validate status.

    Valid statuses:
        active
        inactive
        paused

    Returns:
        normalized status if valid
        None otherwise
    """

    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    if value in VALID_STATUSES:
        return value

    return None


def find_status(row, status_column="Status", visited_columns=None):
    """
    Find and normalize status.

    1. Check expected Status column first.
    2. If invalid/missing, search other unvisited columns.
    3. Return normalized status and source column.
    """

    if visited_columns is None:
        visited_columns = set()

    # ----------------------------------------
    # 1. Check expected Status column
    # ----------------------------------------

    if (
        status_column in row.index
        and status_column not in visited_columns
    ):

        status = normalize_status(row[status_column])

        if status is not None:
            return status, status_column

    # ----------------------------------------
    # 2. Search other unvisited columns
    # ----------------------------------------

    for column in row.index:

        if column == status_column:
            continue

        if column in visited_columns:
            continue

        status = normalize_status(row[column])

        if status is not None:
            return status, column

    return None, None

# Verified

In [ ]:
VALID_VERIFIED = {
    "y": "yes",
    "yes": "yes",
    "n": "no",
    "no": "no"
}


def normalize_verified(value):
    """
    Returns:
        "yes"
        "no"
        None if invalid
    """

    if pd.isna(value):
        return None

    value = str(value).strip().lower()

    return VALID_VERIFIED.get(value)



def find_verified(row, verified_column="verified", visited_columns=None):
    """
    Find and normalize verified status.

    1. Check expected verified column first.
    2. If invalid/missing, search other unvisited columns.
    3. Return normalized value and source column.
    """

    if visited_columns is None:
        visited_columns = set()

    # ----------------------------------------
    # 1. Check expected verified column
    # ----------------------------------------

    if (
        verified_column in row.index
        and verified_column not in visited_columns
    ):

        verified = normalize_verified(row[verified_column])

        if verified is not None:
            return verified, verified_column

    # ----------------------------------------
    # 2. Search other unvisited columns
    # ----------------------------------------

    for column in row.index:

        if column == verified_column:
            continue

        if column in visited_columns:
            continue

        verified = normalize_verified(row[column])

        if verified is not None:
            return verified, column

    return None, None

# Project Completed

In [126]:
def normalize_projects_completed(value):
    """
    Normalize and validate Projects Completed.
    """

    if pd.isna(value):
        return None

    # Convert to string and strip whitespace
    value = str(value).strip()

    if not value:
        return None

    # Must contain ONLY digits
    if not re.fullmatch(r"\d+", value):
        return None

    # Convert to integer
    projects = int(value)

    # Must be between 0 and 20
    if 0 <= projects <= 20:
        return projects

    return None

def find_projects_completed(
    row,
    project_column="Projects Completed",
    visited_columns=None
):
    """
    Find and normalize Projects Completed.

    1. Check expected Projects Completed column first.
    2. If invalid/missing, search other unvisited columns.
    3. Return normalized value and source column.
    """

    if visited_columns is None:
        visited_columns = set()

    # ----------------------------------------
    # 1. Check expected column
    # ----------------------------------------

    if (
        project_column in row.index
        and project_column not in visited_columns
    ):

        projects = normalize_projects_completed(
            row[project_column]
        )

        if projects is not None:
            return projects, project_column

    # ----------------------------------------
    # 2. Search other unvisited columns
    # ----------------------------------------

    for column in row.index:

        if column == project_column:
            continue

        if column in visited_columns:
            continue

        projects = normalize_projects_completed(
            row[column]
        )

        if projects is not None:
            return projects, column

    return None, None

In [109]:
def normalize_data1(data):

    normalized_rows = []

    for _, row in data.iterrows():

        # Each person gets their own visited columns
        visited_columns = set()

        # ----------------------------------------
        # EMAIL
        # ----------------------------------------

        email, email_source_column = find_email(
            row,
            email_column="Email",
            visited_columns=visited_columns
        )

        if email_source_column is not None:
            visited_columns.add(email_source_column)

        # ----------------------------------------
        # PHONE
        # ----------------------------------------

        phone, phone_source_column = find_phone(
            row,
            phone_column="Phone",
            visited_columns=visited_columns
        )

        if phone_source_column is not None:
            visited_columns.add(phone_source_column)

        # ----------------------------------------
        # CITY
        # ----------------------------------------

        city, city_source_column = find_city(
            row,
            city_column="City",
            visited_columns=visited_columns
        )

        if city_source_column is not None:
            visited_columns.add(city_source_column)

        # ----------------------------------------
        # EXPERIENCE
        # ----------------------------------------

        experience, experience_source_column = find_experience(
            row,
            experience_column="Experience (Years)",
            visited_columns=visited_columns
        )

        if experience_source_column is not None:
            visited_columns.add(experience_source_column)

        # ----------------------------------------
        # CTC
        # ----------------------------------------

        ctc, ctc_source_column = find_ctc(
            row,
            ctc_column="Current CTC",
            visited_columns=visited_columns
        )

        if ctc_source_column is not None:
            visited_columns.add(ctc_source_column)

        # ----------------------------------------
        # APPLIED DATE
        # ----------------------------------------

        applied_date, date_source_column = find_date(
            row,
            date_column="Applied Date",
            visited_columns=visited_columns
        )

        if date_source_column is not None:
            visited_columns.add(date_source_column)

        # ----------------------------------------
        # SKILLS
        # ----------------------------------------

        skills, skills_source_columns = find_skills(
            row,
            skill_column="Skills",
            visited_columns=visited_columns
        )

        # Skills may come from multiple columns
        visited_columns.update(skills_source_columns)

        # ----------------------------------------
        # NAME
        # ----------------------------------------

        name, name_source_column = find_name(
            row,
            name_column="Full Name",
            visited_columns=visited_columns
        )

        if name_source_column is not None:
            visited_columns.add(name_source_column)

        # ----------------------------------------
        # CREATE NORMALIZED ROW
        # ----------------------------------------

        normalized_rows.append({
            "name": name,
            "email": email,
            "phone": phone,
            "city": city,
            "experience": experience,
            "ctc": ctc,
            "applied_date": applied_date,
            "skills": skills
        })

    return pd.DataFrame(normalized_rows)

naukari_normalized = normalize_data1(data1)
naukari_normalized.head(5)

C:\Users\Eternity\AppData\Local\Temp\ipykernel_30548\531566021.py:5: UserWarning: Parsing dates in %m/%d/%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  date = pd.to_datetime(
C:\Users\Eternity\AppData\Local\Temp\ipykernel_30548\531566021.py:5: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  date = pd.to_datetime(

,name,email,phone,city,experience,ctc,applied_date,skills
0,tanvi gupta,tanvi.gupta31@example.com,+91-9000000254,bengaluru,4.2,4.1,2026-07-24,"[langchain, mongodb, n8n, rest apis, sql]"
1,manish reddy,manish.reddy73@example.com,+91-9000000237,gurugram,3.5,3.3,2026-08-08,"[docker, javascript, zapier]"
2,priya singh,priya.singh61@mailtest.example.org,+91-9000000287,gurugram,3.0,7.7,2026-08-01,"[mysql, n8n, python, react, sql, zapier]"
3,vikram saxena,vikram.saxena60@example.com,+91-9000000113,gurugram,1.9,6.5,2026-07-07,"[docker, fastapi, react, selenium, sql, web sc..."
4,amit agarwal,amit.agarwal3@mailtest.example.org,+91-9000000288,pune,1.8,4.2,2026-07-19,"[docker, javascript, python, sql]"

In [110]:
data2["status"].unique()

<StringArray>
['Active', 'active', 'ACTIVE', 'Inactive', 'paused', nan, 'Pune']
Length: 7, dtype: str

In [123]:
def normalize_data2(data):

    normalized_rows = []
    
    for _, row in data.iterrows():

        # Each person gets their own visited columns
        visited_columns = set()

        # ----------------------------------------
        # EMAIL
        # ----------------------------------------

        email, email_source_column = find_email(
            row,
            email_column="email_id",
            visited_columns=visited_columns
        )

        if email_source_column is not None:
            visited_columns.add(email_source_column)

        # ----------------------------------------
        # RATE
        # ----------------------------------------

        rate, rate_source_column = find_rate(
            row,
            rate_column="rate",
            visited_columns=visited_columns
        )

        if rate_source_column is not None:
            visited_columns.add(rate_source_column)

        # ----------------------------------------
        # CITY
        # ----------------------------------------

        city, city_source_column = find_city(
            row,
            city_column="location",
            visited_columns=visited_columns
        )

        if city_source_column is not None:
            visited_columns.add(city_source_column)

        # ----------------------------------------
        # STATUS
        # ----------------------------------------

        status, status_source_column = find_status(
            row,
            status_column="Status",
            visited_columns=visited_columns
        )

        if status_source_column is not None:
            visited_columns.add(status_source_column)

        # ------------------------------------------
        # SKILLS
        # -------------------------------------------

        skills, skills_source_columns = find_skills(
            row,
            skill_column="skill_tags",
            visited_columns=visited_columns
        )

        # Skills may come from multiple columns
        visited_columns.update(skills_source_columns)

        # ----------------------------------------
        # NAME
        # ----------------------------------------

        name, name_source_column = find_name(
            row,
            name_column="worker_name",
            visited_columns=visited_columns
        )

        if name_source_column is not None:
            visited_columns.add(name_source_column)

        # ----------------------------------------
        # CREATE NORMALIZED ROW
        # ----------------------------------------

        normalized_rows.append({
            "name": name,
            "email": email,
            "rate": rate,
            "city": city,
            "status": status,
            "skills": skills
        })

    return pd.DataFrame(normalized_rows)

gig_workers = normalize_data2(data2)
gig_workers.head(21)

,name,email,rate,city,status,skills
0,varun jain,varun.jain29@example.com,294.32k/month,pune,active,"[fastapi, mongodb, mysql, n8n, pandas, web scr..."
1,tanvi agarwal,tanvi.agarwal97@example.in,256.048k/month,pune,active,"[fastapi, mongodb, rest apis, web scraping]"
2,karan bhatia,karan.bhatia32@mailtest.example.org,83.824k/month,noida,active,"[javascript, mongodb, selenium, sql, web scrap..."
3,arjun mishra,arjun.mishra70@example.com,91.52k/month,delhi,active,"[docker, javascript, react]"
4,isha kapoor,isha.kapoor54@example.com,15k/month,delhi,active,"[fastapi, javascript, mysql, python, react, se..."
5,isha chopra,isha.chopra95@mailtest.example.org,292.448k/month,pune,active,"[javascript, mysql, react]"
6,meera bhatia,meera.bhatia52@mailtest.example.org,68.64k/month,delhi,active,"[docker, langchain, mysql, python, react, sql]"
7,vikram saxena,vikram.saxena60@example.com,175.344k/month,gurugram,active,"[docker, fastapi, react, selenium, sql, web sc..."
8,rahul chopra,rahul.chopra70@example.com,72k/month,noida,inactive,"[docker, python, zapier]"
9,tanvi gupta,tanvi.gupta31@example.com,276.848k/month,bengaluru,paused,"[langchain, mongodb, n8n, rest apis, sql]"
10,NaN,NaN,NaN,NaN,NaN,[]
11,varun saxena,varun.saxena21@example.in,190.736k/month,gurugram,inactive,"[langchain, mongodb, mysql, rest apis, sql, za..."
12,sneha chopra,sneha.chopra99@example.in,28k/month,pune,active,"[javascript, mysql, pandas, react, sql]"
13,deepak nair,deepak.nair44@example.com,96.72k/month,bengaluru,paused,"[mongodb, n8n, pandas, react]"
14,gaurav mehta,gaurav.mehta79@mailtest.example.org,56k/month,bengaluru,active,"[fastapi, rest apis, selenium, sql]"
15,neha bhatia,neha.bhatia60@mailtest.example.org,79k/month,pune,active,"[fastapi, javascript, selenium, zapier]"
16,arjun mehta,arjun.mehta77@mailtest.example.org,42k/month,noida,inactive,"[docker, fastapi, mysql, pandas, web scraping,..."
17,manish bhatia,manish.bhatia3@example.com,73k/month,noida,active,"[docker, javascript, pandas, react, rest apis,..."
18,isha chopra,isha.chopra95@mailtest.example.org,292.448k/month,pune,active,"[javascript, mysql, react]"
19,divya chopra,divya.chopra59@example.in,55k/month,noida,inactive,"[docker, fastapi, mongodb, zapier]"
20,karan chopra,karan.chopra76@mailtest.example.org,90.896k/month,pune,active,"[mongodb, n8n, pandas, python, selenium]"

In [127]:
def normalize_data3(data):

    normalized_rows = []
        
    for _, row in data.iterrows():

        # Each person gets their own visited columns
        visited_columns = set()

        # ----------------------------------------
        # PHONE
        # ----------------------------------------

        phone, phone_source_column = find_phone(
            row,
            phone_column="Phone Number",
            visited_columns=visited_columns
        )

        if phone_source_column is not None:
            visited_columns.add(phone_source_column)

        # ----------------------------------------
        # CITY
        # ----------------------------------------

        city, city_source_column = find_city(
            row,
            city_column="City",
            visited_columns=visited_columns
        )

        if city_source_column is not None:
            visited_columns.add(city_source_column)

        # ----------------------------------------
        # VERIFIED
        # ----------------------------------------

        verified, verified_source_column = find_verified(
            row,
            verified_column="Verified",
            visited_columns=visited_columns
        )

        if verified_source_column is not None:
            visited_columns.add(verified_source_column)


        # ---------------------------------------
        # PROJECTS COMPLETED
        # ----------------------------------------

        projects_completed, projects_source_column = find_projects_completed(
            row,
            project_column="Projects Completed",
            visited_columns=visited_columns
        )

        if projects_source_column is not None:
            visited_columns.add(projects_source_column)
        

        # ----------------------------------------
        # NAME
        # ----------------------------------------

        name, name_source_column = find_name(
            row,
            name_column="worker_name",
            visited_columns=visited_columns
        )

        if name_source_column is not None:
            visited_columns.add(name_source_column)

        # ----------------------------------------
        # CREATE NORMALIZED ROW
        # ----------------------------------------

        normalized_rows.append({
            "name": name,
            "phone": phone,
            "city": city,
            "verified": verified,
            "projects_completed": projects_completed
        })

    return pd.DataFrame(normalized_rows)

cbnexus_contacts = normalize_data3(data3)
cbnexus_contacts.head(21)

              name           phone       city verified  projects_completed
0       rohit nair  +91-9000000268   gurugram      yes                13.0
1      ritu sharma  +91-9000000146      noida      yes                15.0
2     priya saxena  +91-9000000231      delhi       no                12.0
3      arjun mehta  +91-9000000131      noida       no                 9.0
4     nikhil mehta  +91-9000000104       pune      yes                10.0
5   rahul malhotra  +91-9000000260      delhi       no                 4.0
6     deepak mehta  +91-9000000116      noida      yes                11.0
7   sahil malhotra  +91-9000000143      noida       no                 0.0
8     shreya gupta  +91-9000000227      noida      yes                13.0
9      priya singh  +91-9000000287   gurugram      yes                 3.0
10      varun jain  +91-9000000263       pune      yes                14.0
11   tanvi agarwal  +91-9000000148       pune       no                 3.0
12    karan bhatia  +91-9000000211      noida      yes                 2.0
13    arjun mishra  +91-9000000106      delhi       no                10.0
14            name             NaN        NaN      NaN                 NaN
15     isha kapoor  +91-9000000295      delhi      yes                 6.0
16     isha chopra  +91-9000000138       pune       no                 7.0
17    meera bhatia  +91-9000000223      delhi       no                 4.0
18   vikram saxena  +91-9000000113   gurugram       no                15.0
19    rahul chopra  +91-9000000137      noida       no                10.0
20     tanvi gupta  +91-9000000254  bengaluru       no                14.0

In [128]:
naukari_normalized.info(), gig_workers.info(), cbnexus_contacts.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          41 non-null     str
 1   email         42 non-null     str
 2   phone         42 non-null     str
 3   city          42 non-null     str
 4   experience    42 non-null     float64
 5   ctc           42 non-null     float64
 6   applied_date  42 non-null     object
 7   skills        42 non-null     object
dtypes: float64(2), object(2), str(4)
memory usage: 2.8+ KB
<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    31 non-null     str
 1   email   31 non-null     str
 2   rate    31 non-null     str
 3   city    31 non-null     str
 4   status  31 non-null     str
 5   skills  32 non-null     object
dtypes: object(1), str(5)
memory usage: 1.6+ KB
<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                31 non-null     str
 1   phone               30 non-null     str
 2   city                30 non-null     str
 3   verified            30 non-null     str
 4   projects_completed  30 non-null     float64
dtypes: float64(1), str(4)
memory usage: 1.3 KB

(None, None, None)